server:
  port: ${PORT:0}
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: srv-user
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:srv_user}
    username: ${POSTGRES_USER:srv_user}
    password: ${POSTGRES_PASSWORD:srv_user}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: ${EUREKA_HOSTNAME:http://localhost:8761/eureka/}
