scrape_configs:
  - job_name: 'conectar-saude-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['srv-api-gateway', 'srv-api-gateway:8765', 'localhost:8765']
        labels:
          application: 'ConectarSaude'
