server:
  port: ${PORT:0}
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: srv-oauth
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com

jwt:
  secret: ${JWT_SECRET}
  expiration: 300

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    service-url:
      defaultZone: ${EUREKA_HOSTNAME:http://localhost:8761/eureka/}